// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyB9Nj_2wuvzx4rhYIjbXnhqMzpeuGQZhj0",
  authDomain: "nextjs-firebase-auth-b3f79.firebaseapp.com",
  projectId: "nextjs-firebase-auth-b3f79",
  storageBucket: "nextjs-firebase-auth-b3f79.appspot.com",
  messagingSenderId: "334377050884",
  appId: "1:334377050884:web:3a082abca2a9453fa6e651"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);